//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string DealerCode { get; set; }
        public string CusCode { get; set; }
        public string GuestID { get; set; }
        public string CusDesc { get; set; }
        public string FatherHusName { get; set; }
        public string AuxCusCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string ContPerson { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public string NIC { get; set; }
        public string CusTypeCode { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string CellNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string NTNno { get; set; }
        public Nullable<double> AdvanceReceipt { get; set; }
        public string AccountCode { get; set; }
        public string UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdTerm { get; set; }
        public string SalesTaxRegNo { get; set; }
        public string Behavior { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<long> CustomerKey { get; set; }
        public string ApplyUnRegSalesTaxFlag { get; set; }
        public string IsPvtLtd { get; set; }
        public string CountryCode { get; set; }
        public string StateCode { get; set; }
        public string CityCode { get; set; }
        public string CSGNo { get; set; }
        public string MCNo { get; set; }
        public string Title { get; set; }
    }
}
