//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXBMS.Model
{
    using System;
    using System.Collections.Generic;

    public partial class FormVerification
    {
     
        public string DealerCode { get; set; }
        public string UserCode { get; set; }
        public string FormCode { get; set; }
        public string FormName { get; set; }
        public string FormActionCode { get; set; }
        public string FormActionName { get; set; }
        public string ActionValue { get; set; }
        

    }
}
