//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CRM_V3.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CustomerDBModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CustomerDBModelContainer object using the connection string found in the 'CustomerDBModelContainer' section of the application configuration file.
        /// </summary>
        public CustomerDBModelContainer() : base("name=CustomerDBModelContainer", "CustomerDBModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomerDBModelContainer object.
        /// </summary>
        public CustomerDBModelContainer(string connectionString) : base(connectionString, "CustomerDBModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomerDBModelContainer object.
        /// </summary>
        public CustomerDBModelContainer(EntityConnection connection) : base(connection, "CustomerDBModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
